services:
  cq-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cq-manager
    image: cq-manager:latest
    ports:
      - "8000:8000"
    volumes:
      - ./database:/usr/src/app/database
